version: '3'
services:
  traefik:
    image: traefik:2.9.5
    restart: unless-stopped
    ports:
      - "80:80"
      - "8080:8080"
      - "443:443"
    volumes:
      - ./config/traefik:/etc/traefik